if __name__ == "__main__":
    lst = list()
    lst.append(1)
    lst.append(2)
    print("After appending values.")
    print(lst)
    print("After appending list.")
    lst.extend([3, 4, 5])
    print(lst)
    print("After inserting at 0 th position.")
    lst.insert(0, 6)
    print(lst)
    lst.sort()
    print("After sorting.")
    print(lst)
    lst.pop()
    print(lst)
    lst.remove(2)
    print(lst)
    lst.reverse()
    print(lst)
    print(lst[3:])